### ISSUE TITLE
fillGradient not working when used with createGraphics()

### ISSUE THREAD

**Issue by mikima** [alterebro/p5.fillGradient#4]
if you want to use the fillGradient when using [createGraphics()](https://p5js.org/reference/p5/createGraphics/) it seems not working and returns just a white fill.

**Comment by alterebro** [comment]
Hi @mikima you need to pass the graphics buffer as a third parameter to the fillGradient function: `fillGradient(type, properties, context)`.
I've added a working sample on the `/examples` folder. [p5.fillGradient.createGraphics.example.html](https://github.com/alterebro/p5.fillGradient/blob/main/examples/p5.fillGradient.createGraphics.example.html)

**Comment by mikima** [comment]
Thanks!

**Comment by ffd8** [comment]
Ahaa – this just got me too! Would be super helpful if the readme/docs had a blurb about this.
